service: IndraStarWarsAPI


provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: api
  environment:
    DYNAMODB_TABLE: StarWarsModelsTable
    START_WARS_API: https://swapi.py4e.com/api
    port: 3000

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

resources:
  Resources:
    StarWarsModelsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-prune-plugin
  - serverless-dynamodb-local
  - serverless-offline
